Add meta data to output contexts
JetXu-LLM/llama-github pull request #15
Opened 2024-06-11 15:32 UTC by balachander712

Issue link: https://github.com/JetXu-LLM/llama-github/issues

- Modified the `retrieve_context` function to add metadata to the output context strings.
- The new output context will be in the format:
```
[
	{
		'context': 'some_context_string',
		'url': 'relevant_url_1;'
	},
	{
		'context': 'some_context_string',
		'url': 'relevant_url_2;'
	},
	{
		'context': 'some_context_string',
		'url': 'relevant_url_3;'
	},
]

2024-06-12 14:43 UTC, JetXu-LLM commented
Hi @balachander712 ,

Thank you for your contribution and for addressing the issue with adding metadata to the output contexts. I appreciate the effort you've put into this PR 😄

I wanted to let you know that I am currently quite busy with other tasks and may not be able to review your code until this weekend. I will make sure to go through it thoroughly and provide my feedback by then.

Thank you for your patience and understanding.

Best regards,
Jet Xu.

2024-06-15 09:21 UTC, JetXu-LLM commented on llama_github/rag_processing/rag_processor.py
> +            url = result.get('url', '')
For the repo search result, please notice that the initial search result (refer to `github_rag.py` lines 330-334) only contains the following parameters:

```python
results_with_index.append({
    'index': index,
    'full_name': repository.full_name,
    'content': repo_readme,
})
```

We need to compose the final URL by using `full_name`. Please kindly help to rewrite the code accordingly.

2024-06-15 13:34 UTC, JetXu-LLM commented on llama_github/rag_processing/rag_processor.py
> +            url = result.get('url', '')
The `url` parameter from the search issue result list comes from the GitHub Search Issue API, which provides an issue API URL (e.g., `https://api.github.com/repos/quarkusio/quarkus/issues/1957`). This is not the HTML URL. We could consider transforming it to the official GitHub issue webpage URL (e.g., `https://github.com/quarkusio/quarkus/issues/1957`).

Please kindly update the code to reflect this change.

2024-06-15 13:45 UTC, JetXu-LLM requested changes
Thank you for your contributions! The changes are looking good overall. There are a couple of adjustments needed regarding the URL handling for repository search results and issue URLs. Please refer to the comments for specific details. If there are any questions or if anything is unclear, please don't hesitate to let me know.

Looking forward to the updated code. Thanks again for your effort!

2024-06-15 13:48 UTC, balachander712 commented
Hi @JetXu-LLM looking into the comments

2024-06-18 14:26 UTC, JetXu-LLM commented
> Hi @JetXu-LLM looking into the comments

Hi @balachander712,

I hope you're doing well. I wanted to check in regarding the updates needed for the URL handling in your PR #15. Your contribution is greatly appreciated, and the changes are looking good overall. 

When you have a moment, could you please address the comments and update the code accordingly? Your timely updates will help us keep the project moving forward smoothly. If you encounter any issues or need further clarification on the review comments, feel free to reach out. I'm here to assist you.

Thank you again for your efforts and contributions to the llama-github project. Looking forward to your updated code 🙂

Best regards,  
Jet Xu

2024-06-18 14:37 UTC, balachander712 commented
Hi @JetXu-LLM , Sorry didn't get time to look into it as I was stuck with something else. Will look into it and resolve the comments within a day or two.

2024-06-19 12:01 UTC, JetXu-LLM commented
> Hi @JetXu-LLM , Sorry didn't get time to look into it as I was stuck with something else. Will look into it and resolve the comments within a day or two.

Hi @balachander712,

No worries, thank you for the update! I appreciate your effort and look forward to your changes.

Best regards,
Jet Xu

2024-06-22 18:32 UTC, balachander712 commented
Hi @JetXu-LLM Sorry for the delay, got stuck with work.
Have made the requested changes. Please review it and let me know if any more changes are required

2024-06-23 08:52 UTC, merged

2024-06-23 08:53 UTC, JetXu-LLM commented
> Hi @JetXu-LLM Sorry for the delay, got stuck with work. Have made the requested changes. Please review it and let me know if any more changes are required

Hi @balachander712,

Thank you for your excellent contribution! The changes look great and address the issue effectively. I have reviewed the code and it meets the project's requirements.

Merging this now. Looking forward to more contributions from you!

Best regards,

Jet Xu